[package]
name = "day07"
version = "0.1.0"
edition = "2021"

[dependencies]
bit-set = "0.8.0"
itertools = "0.13.0"
petgraph = "0.6.5"
rayon = "1.10.0"
regex = "1.11.1"
scan_fmt = "0.2.6"
stopwatch = "0.0.7"
thiserror = "2.0.4"
