[package]
name = "day05"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.13.0"
petgraph = "0.6.5"
regex = "1.11.1"
roaring = "0.10.7"
scan_fmt = "0.2.6"
scanf = "1.2.1"
thiserror = "2.0.4"
